@startuml

Посетитель -- (Получить заказ)
Посетитель -- (Оформить заказ)

(Оформить заказ) ..> (Посмотреть меню) : <<include>>
(Оформить заказ) ..> (Добавить позицию в корзину) : <<include>>
(Оформить заказ) ..> (Оплатить заказ) : <<include>>

(Оплатить заказ) <|-- (Оплатить наличными)
(Оплатить заказ) <|-- (Оплатить картой)
(Оплатить заказ) <|-- (Оплатить бонусами)

(Оплатить заказ) <.. (Получить подарок) : <<extend>>
(Оплатить заказ) <.. (Получить скидку) : <<extend>>

(Получить заказ) <.. (Посмотреть статус заказа на табло) : <<extend>>
(Получить заказ) <.. (Посмотреть статус заказа в приложении) : <<extend>>

(Посмотреть меню) <.. (Посмотреть информацию о позиции меню) : <<extend>>
(Добавить позицию в корзину) <.. (Изменить содержимое корзины) : <<extend>>

(Оформить заказ) <.. (Авторизоваться в программе лояльности) : <<extend>>
(Зарегистрироваться в программе лояльности) <.. (Авторизоваться в программе лояльности) : <<include>>

(Авторизоваться в программе лояльности) ..> (Просмотреть информацию в ЛК) : <<extend>>
(Изменить данные в ЛК) ..> (Просмотреть информацию в ЛК) : <<extend>>
(Посмотреть историю заказов) ..> (Просмотреть информацию в ЛК) : <<extend>>
(Посмотреть информацию о бонусах) ..> (Просмотреть информацию в ЛК) : <<extend>>

@enduml
